source: ''
paths: {}
collections_config: {}
collection_groups:
_enabled_editors:
commit_templates: []
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
base_url:
editor:
source_editor:
timezone: Etc/UTC
